import{a as w,S as E,i as n}from"./assets/vendor-df5IXrWy.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const v="51406167-def03c354fee4f6bc11ceafbb",S="https://pixabay.com/api/",P=15;async function f(r,o=1){const e={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:P};try{return(await w.get(S,{params:e})).data}catch{throw new Error("Failed to fetch images")}}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more");let q=new E(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const o=r.map(e=>`
        <li class="gallery-item">
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </li>`).join("");m.insertAdjacentHTML("beforeend",o),q.refresh()}function M(){m.innerHTML=""}function p(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}function L(){y.classList.remove("hidden")}function l(){y.classList.add("hidden")}const B=document.querySelector(".form"),R=document.querySelector(".load-more");let a=1,d="",u=0;B.addEventListener("submit",$);R.addEventListener("click",O);async function $(r){r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(!o){n.error({title:"Error",message:"Please enter a search term!"});return}d=o,a=1,M(),l(),p();try{const e=await f(d,a);if(e.hits.length===0){n.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(e.hits),u=Math.ceil(e.totalHits/15),a<u?L():(l(),n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"Error",message:"Something went wrong while fetching images!"})}finally{b()}}async function O(){a+=1,p(),l();try{const r=await f(d,a);g(r.hits),x(),a<u?L():n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})}catch{n.error({title:"Error",message:"Failed to load more images."})}finally{b()}}function x(){const r=document.querySelector(".gallery-item");if(r){const o=r.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
